//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDetailed
    {
        public int ID { get; set; }
        public int WorkOrderID { get; set; }
        public int ServiceID { get; set; }
        public int ServiceQuantity { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
