//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.Invoices = new HashSet<Invoice>();
            this.WorkOrderDetaileds = new HashSet<WorkOrderDetailed>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeID { get; set; }
        public int VehicleID { get; set; }
        public int VehicleKm { get; set; }
        public System.DateTime DateTime { get; set; }
        public int IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<WorkOrderDetailed> WorkOrderDetaileds { get; set; }
    }
}
